[build]
  publish = "/"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "gate"
  path = "/premium/*"

[[redirects]]
  from = "/activate"
  to = "/.netlify/functions/activate"
  status = 200
  force = true

[[redirects]]
  from = "/activate/*"
  to = "/.netlify/functions/activate"
  status = 200
  force = true
